<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Evidos – Signhost REST API - OpenAPI v3
 *
 * Signing online documents - Easy and legally valid
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.15
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addFile
     *
     * Add File to the transaction.
     *
     */
    public function testAddFile()
    {
    }

    /**
     * Test case for createTransactionExample
     *
     * Create Transaction - Example.
     *
     */
    public function testCreateTransactionExample()
    {
    }

    /**
     * Test case for fileReceiptTransactionIdGet
     *
     * .
     *
     */
    public function testFileReceiptTransactionIdGet()
    {
    }

    /**
     * Test case for startTransaction
     *
     * Start Transaction.
     *
     */
    public function testStartTransaction()
    {
    }

    /**
     * Test case for transactionTransactionIdDelete
     *
     * Delete a transaction.
     *
     */
    public function testTransactionTransactionIdDelete()
    {
    }

    /**
     * Test case for transactionTransactionIdFileFileIdGet
     *
     * .
     *
     */
    public function testTransactionTransactionIdFileFileIdGet()
    {
    }

    /**
     * Test case for transactionTransactionIdGet
     *
     * Get information about a transaction.
     *
     */
    public function testTransactionTransactionIdGet()
    {
    }
}
